### PR TITLE
Handle malformed Card#authorUrl parsing

### PR DESCRIPTION
**Pull request by abraham**
I ran across https://mastodon.social/@GIbiz/109626791400616879 which returns a malformed `author_url` value.

```
"author_url": "[\"https://www.gamesindustry.biz/authors/brendan-sinclair\", \"https://twitter.com/BrendanSinclair\"]",
```

### CODE REVIEW

**Comment by lukepighetti** [comment]
If I understand correctly... what if we made the `authorUrl` field a `List<Uri>` and then made a custom deserializer that can handle both a single `Uri` value and multiple encoded as a JSON list? 

If that doesn't make any sense, then this looks fine to me

**Comment by abraham** [comment]
I've switched it to the simpler `Uri.tryParse`. This case feels like the exception not the rule and a bug in Mastodon so I'll try and get a bug fix implemented there.

**Comment by lukepighetti** [comment]
Looks like generate step can't push to your branch, you'll have to regenerate and push manually

**Comment by abraham** [comment]
Updated.

**Pull request merged**
