### PR TITLE
Rename mastodon_dart to mastodon

### PR DESCRIPTION
**Pull request by abraham**
I randomly ran across https://github.com/mykdavies/Mastodon/issues/1. This updates the code so it can be published to https://pub.dev/packages/mastodon.

### CODE REVIEW

**Comment by lukepighetti** [comment]
Any thoughts on pros / cons on migrating the name at this point?

**Comment by abraham** [comment]
The main pro would probably be the "SEO". The "mastodon" package is the [first result](https://pub.dev/packages?q=mastodon) even though it has lower likes, points, and popularity. I personally like the cleaner imports but I'm vain like that 😆.

```diff
-import 'package:mastodon_dart/mastodon_dart.dart';
+import 'package:mastodon/mastodon.dart';
```

Con would be devs using `mastodon_dart` would have to migrate. Although it's basically a find and replace for `package:mastodon_dart/mastodon_dart`.

**Comment by lukepighetti** [comment]
I think my main concern is that if we use `mastodon` then I don't have full control over the package, I'm just added as an uploader. @GroovinChip care to weigh in?

**Comment by GroovinChip** [comment]
We named the package as we did because we were also maintaining a Flutter package. The naming distinguishes it as being a pure Dart package. I believe the name should remain as it is.

**Comment by GroovinChip** [comment]
Not to mention we are already to official mastodon Dart client. Says so in their docs ;)

**Comment by abraham** [comment]
The docs just link to the other package. https://docs.joinmastodon.org/client/libraries/#dart

> We named the package as we did because we were also maintaining a Flutter package.

That suggests to me that it's no longer a reason to use the `_dart` name.

**Comment by abraham** [comment]
I really don't care one way or the other. I saw that issue and thought changing the name would be better long term for the project.

**Comment by GroovinChip** [comment]
@lukepighetti ball's in your court

**Comment by lukepighetti** [comment]
We used to be on their website, I wonder if we were removed when I deprecated this package (before opening it up post Twitter acquisition)

**Comment by lukepighetti** [comment]
I opened a PR to fix the official docs https://github.com/mastodon/documentation/pull/1164 so that it's at least correct

I don't feel comfortable closing this ticket yet until there is consensus

**Comment by GroovinChip** [comment]
IMO even though `mastodon_flutter` is deprecated at the moment, keeping the naming as-is is beneficial in that it
A) Distinguishes this package as a Dart from others that may be Flutter packages
B) Keeps the distinction in case we decide in the future to reverse the deprecation of `mastodon_flutter`

**Comment by lukepighetti** [comment]
@Abraham I'm going to close this, reasons:

1) I don't like the idea of someone who isn't actively developing the package having full control over the pub entry
2) mastodon team is usually pretty good at merging website changes like https://github.com/mastodon/documentation/pull/1164
3) migration awareness concerns

**Pull request closed without merging**
